# Generated by Django 4.1.5 on 2023-02-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('profissao1', models.CharField(max_length=100, verbose_name='Profissção 1')),
                ('profissao2', models.CharField(max_length=100, verbose_name='Profissão 2')),
                ('github', models.CharField(default='#', max_length=100, verbose_name='GitHub')),
                ('linkedin', models.CharField(default='#', max_length=100, verbose_name='Linkedin')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
                ('cidade_estado', models.CharField(max_length=100, verbose_name='Cidade, Estado')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
