# Generated by Django 4.1.5 on 2023-02-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('ano_conclusao', models.CharField(max_length=100, verbose_name='Ano de Conclusão')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
