# Generated by Django 4.1.5 on 2023-02-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conhecimento_cursos_experiencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('area', models.CharField(max_length=100, verbose_name='Area')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
